export const FACILITIES = {
    1: {
        label: '智能系统',
        icon1: require('../../../images/icons/buildFacilitiesIcon/zhinengxt1.png'),
        icon2: require('../../../images/icons/buildFacilitiesIcon/zhinengxt2.png'),
        type: new Set([3]),
    },
    2: {
        label: '空调系统',
        icon1: require('../../../images/icons/buildFacilitiesIcon/ktxt1.png'),
        icon2: require('../../../images/icons/buildFacilitiesIcon/ktxt2.png'),
        type: new Set([3]),
    },
    3: {
        label: '集中供暖',
        icon1: require('../../../images/icons/buildFacilitiesIcon/jzgn1.png'),
        icon2: require('../../../images/icons/buildFacilitiesIcon/jzgn2.png'),
        type: new Set([3]),
    },
    4: {
        label: '办公家具',
        icon1: require('../../../images/icons/buildFacilitiesIcon/bgjj1.png'),
        icon2: require('../../../images/icons/buildFacilitiesIcon/bgjj2.png'),
        type: new Set([3]),
    },
    5: {
        label: '免费车位',
        icon1: require('../../../images/icons/buildFacilitiesIcon/mianfeicw1.png'),
        icon2: require('../../../images/icons/buildFacilitiesIcon/mianfeicw2.png'),
        type: new Set([3]),
    },
    6: {
        label: '员工餐厅',
        icon1: require('../../../images/icons/buildFacilitiesIcon/ygct1.png'),
        icon2: require('../../../images/icons/buildFacilitiesIcon/ygct2.png'),
        type: new Set([3]),
    },
    7: {
        label: '安全监控',
        icon1: require('../../../images/icons/buildFacilitiesIcon/anquanjk1.png'),
        icon2: require('../../../images/icons/buildFacilitiesIcon/anquanjk2.png'),
        type: new Set([3]),
    },
    8: {
        label: '会所服务',
        icon1: require('../../../images/icons/buildFacilitiesIcon/hsfw1.png'),
        icon2: require('../../../images/icons/buildFacilitiesIcon/hsfw2.png'),
        type: new Set([3]),
    },
    9: {
        label: '消防层',
        icon1: require('../../../images/icons/buildFacilitiesIcon/xiaofangc1.png'),
        icon2: require('../../../images/icons/buildFacilitiesIcon/xiaofangc2.png'),
        type: new Set([3]),
    },
    10: {
        label: '楼梯间',
        icon1: require('../../../images/icons/buildFacilitiesIcon/loutij1.png'),
        icon2: require('../../../images/icons/buildFacilitiesIcon/loutij2.png'),
        type: new Set([3]),
    },
    11: {
        label: '电梯',
        icon1: require('../../../images/icons/buildFacilitiesIcon/dianti1.png'),
        icon2: require('../../../images/icons/buildFacilitiesIcon/dianti2.png'),
        type: new Set([3]),
    },
    12: {
        label: '卫生间',
        icon1: require('../../../images/icons/buildFacilitiesIcon/weishengjian1.png'),
        icon2: require('../../../images/icons/buildFacilitiesIcon/weishengjian2.png'),
        type: new Set([3]),
    },
    13: {
        label: '咖啡吧',
        icon1: require('../../../images/icons/buildFacilitiesIcon/kafeib1.png'),
        icon2: require('../../../images/icons/buildFacilitiesIcon/kafeib2.png'),
        type: new Set([3]),
    },
    14: {
        label: 'Wi-Fi',
        icon1: require('../../../images/icons/buildFacilitiesIcon/WIFI1.png'),
        icon2: require('../../../images/icons/buildFacilitiesIcon/WIFI2.png'),
        type: new Set([3]),
    },
    15: {
        label: '自动取款机',
        icon1: require('../../../images/icons/buildFacilitiesIcon/ATM1.png'),
        icon2: require('../../../images/icons/buildFacilitiesIcon/ATM2.png'),
        type: new Set([3]),
    },
    16: {
        label: '会议室',
        icon1: require('../../../images/icons/buildFacilitiesIcon/huiyis1.png'),
        icon2: require('../../../images/icons/buildFacilitiesIcon/huiyis2.png'),
        type: new Set([3]),
    },
    17: {
        label: '共享空间',
        icon1: require('../../../images/icons/buildFacilitiesIcon/gxkj1.png'),
        icon2: require('../../../images/icons/buildFacilitiesIcon/gxkj2.png'),
        type: new Set([4]),
    },
    18: {
        label: '消防设施',
        icon1: require('../../../images/icons/buildFacilitiesIcon/anquanss1.png'),
        icon2: require('../../../images/icons/buildFacilitiesIcon/anquanss2.png'),
        type: new Set([4]),
    },
    19: {
        label: '楼梯间',
        icon1: require('../../../images/icons/buildFacilitiesIcon/loutij1.png'),
        icon2: require('../../../images/icons/buildFacilitiesIcon/loutij2.png'),
        type: new Set([4]),
    },
    20: {
        label: '空调系统',
        icon1: require('../../../images/icons/buildFacilitiesIcon/ktxt1.png'),
        icon2: require('../../../images/icons/buildFacilitiesIcon/ktxt2.png'),
        type: new Set([4]),
    },
    21: {
        label: '集中供暖',
        icon1: require('../../../images/icons/buildFacilitiesIcon/jzgn1.png'),
        icon2: require('../../../images/icons/buildFacilitiesIcon/jzgn2.png'),
        type: new Set([4]),
    },
    22: {
        label: '智能系统',
        icon1: require('../../../images/icons/buildFacilitiesIcon/zhinengxt1.png'),
        icon2: require('../../../images/icons/buildFacilitiesIcon/zhinengxt2.png'),
        type: new Set([4]),
    },
    23: {
        label: '停车位',
        icon1: require('../../../images/icons/buildFacilitiesIcon/tingchewei1.png'),
        icon2: require('../../../images/icons/buildFacilitiesIcon/tingchewei2.png'),
        type: new Set([4]),
    },
    24: {
        label: '排污管道',
        icon1: require('../../../images/icons/buildFacilitiesIcon/paiwugd1.png'),
        icon2: require('../../../images/icons/buildFacilitiesIcon/paiwugd2.png'),
        type: new Set([4]),
    },
    25: {
        label: '烟道',
        icon1: require('../../../images/icons/buildFacilitiesIcon/yandao1.png'),
        icon2: require('../../../images/icons/buildFacilitiesIcon/yandao2.png'),
        type: new Set([4]),
    },
    26: {
        label: '电梯',
        icon1: require('../../../images/icons/buildFacilitiesIcon/dianti1.png'),
        icon2: require('../../../images/icons/buildFacilitiesIcon/dianti2.png'),
        type: new Set([4]),
    },
    27: {
        label: '24小时安保',
        icon1: require('../../../images/icons/buildFacilitiesIcon/anbao1.png'),
        icon2: require('../../../images/icons/buildFacilitiesIcon/anbao2.png'),
        type: new Set([4]),
    },
    28: {
        label: '天然气',
        icon1: require('../../../images/icons/buildFacilitiesIcon/tianranqi1.png'),
        icon2: require('../../../images/icons/buildFacilitiesIcon/tianranqi2.png'),
        type: new Set([4]),
    },
}
